services:
  - type: web
    name: btp-smart-tools
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: BTP_PUBLIC_URL
        value: https://btpsmarttools.com
      - key: MYPVIT_MODE
        value: TEST
      - key: MYPVIT_BASE_URL
        value: https://api.mypvit.pro
      - key: MYPVIT_MERCHANT_SLUG
        value: MR_1778797178
      - key: MYPVIT_SECRET_RECEIVER_TOKEN
        value: pvit-btp-b9a1c7a2759644a7b005
